name: CI

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
  workflow_call: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      # Build for GitHub Pages on main, normal build otherwise.
      - uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6.1.2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - run: npm run build
        if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/main') }}
  deploy:
    needs: test
    runs-on: ubuntu-26.04-arm
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        id: deployment
